### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by dlhenke** [joco-nz/lcnc-bullseye-installer#6]
n/tmp/usr/share/linuxcnc/linuxcnc-wizard.gif debian/tmp/usr/share/linuxcnc/linuxcnc.gif debian/tmp/usr/share/linuxcnc/linuxcnc.nml debian/tmp/usr/share/linuxcnc/linuxcnc_big.nml debian/tmp/usr/share/linuxcnc/linuxcncicon.png debian/tmp/usr/share/linuxcnc/ncfiles/ debian/tmp/usr/share/linuxcnc/pncconf/ debian/tmp/usr/share/linuxcnc/popupkeyboard.ui debian/tmp/usr/share/linuxcnc/stepconf/ debian/tmp/usr/share/linuxcnc/touchy.glade debian/linuxcnc-uspace//usr/share/linuxcnc/
	install -d debian/linuxcnc-uspace//usr/share/man/man1
	cp --reflink=auto -a debian/tmp/usr/share/man/man1/5axisgui.1 debian/tmp/usr/share/man/man1/axis-remote.1 debian/tmp/usr/share/man/man1/axis.1 debian/tmp/usr/share/man/man1/debuglevel.1 debian/tmp/usr/share/man/man1/elbpcom.1 debian/tmp/usr/share/man/man1/gladevcp.1 debian/tmp/usr/share/man/man1/gladevcp_demo.1 debian/tmp/usr/share/man/man1/gmoccapy.1 debian/tmp/usr/share/man/man1/gremlin_view.1 debian/tmp/usr/share/man/man1/gs2_vfd.1 debian/tmp/usr/share/man/man1/gscreen.1 debian/tmp/usr/share/man/man1/hal-histogram.1 debian/tmp/usr/share/man/man1/hal_input.1 debian/tmp/usr/share/man/man1/hal_manualtoolchange.1 debian/tmp/usr/share/man/man1/hal_parport.1 debian/tmp/usr/share/man/man1/halcmd.1 debian/tmp/usr/share/man/man1/halcmd_twopass.1 debian/tmp/usr/share/man/man1/halmeter.1 debian/tmp/usr/share/man/man1/halreport.1 debian/tmp/usr/share/man/man1/halrmt.1 debian/tmp/usr/share/man/man1/halrun.1 debian/tmp/usr/share/man/man1/halsampler.1 debian/tmp/usr/share/man/man1/halscope.1 debian/tmp/usr/share/man/man1/halshow.1 debian/linuxcnc-uspace//usr/share/man/man1/
	install -d debian/.debhelper/generated/linuxcnc-uspace
dh_install: error: missing files, aborting
make: *** [debian/rules:38: binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
dpkg: error: cannot access archive 'linuxcnc-uspace_2.9.0~pre0_amd64.deb': No such file or directory

**Comment by joco-nz** [comment]
Script updated with recent dependency changes.
Tested and proven to work including to a working probe basic sim.

**Comment by Moshkopp** [comment]
tested today and worked for me as well

**Comment by joco-nz** [comment]
CLosing as believe is now resolved.
