### ISSUE TITLE
`Need to update for 2.9 branch as master = 2.10 now

### ISSUE THREAD

**Issue by rodw-au** [joco-nz/lcnc-bullseye-installer#9]

**Comment by rodw-au** [comment]
```
	git clone https://github.com/LinuxCNC/linuxcnc.git ~/dev/linuxcnc/rip
       git checkout 2.9  <-------------------------------------------------------------- add this: checkout 2.9 branch
	cd ~/dev/linuxcnc/rip/src/
	./autogen.sh
	./configure --with-realtime=uspace
```
Or change the name for the deb when installing but I think this would be better.

**Comment by attentiondeficitdisasters** [comment]
I've actually got a pull request in for that along with creating an environment variable to name the package the same way dpkg does. :-)

**Comment by rodw-au** [comment]
Nice, This can be closed. I'll see if I can grab Joco's disordered attention. :)

**Comment by joco-nz** [comment]
Merged referenced pull request.
